version: '2'
services:
  web:
    build: .
    command: java -Dserver.port=4567 -jar ./build/libs/OnboardingJSONInterpreter-0.1.jar
    ports:
      - "4567:4567"
    volumes:
      - .:/OnbaordingJSONInterpreter
